packages:
  - graphql
  - web

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
