[build]
watchPatterns = ["shared/**", "web/**"]
installCommand = "corepack enable && pnpm install"
buildCommand = "pnpm --filter @highforthis/web build && pnpm --filter @highforthis/web prod:upload"

[deploy]
startCommand = "pnpm --filter @highforthis/web start"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
